import React, { useState } from 'react';
import { Deal, UnderwritingMetrics } from '../../types/spreading';
import { formatCurrency, formatRatio } from '../../utils/financialMath';
import { X, Printer, Download, FileCheck } from 'lucide-react';

interface CreditMemoModalProps {
  isOpen: boolean;
  onClose: () => void;
  deal: Deal;
  metrics: UnderwritingMetrics;
  rateHike: number;
}

export const CreditMemoModal: React.FC<CreditMemoModalProps> = ({
  isOpen,
  onClose,
  deal,
  metrics,
  rateHike,
}) => {
  const [analystNotes, setAnalystNotes] = useState<string>(
    'Borrower demonstrates consistent gross margin stability above 40% and solid liquidity. Officer compensation contains $320k discretionary excess which was verified and added back per credit policy. DSCR remains above 1.30x even under a +100 bps rate shock.'
  );
  const [signOffName, setSignOffName] = useState<string>(deal.creditOfficer);
  const [isExported, setIsExported] = useState<boolean>(false);

  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleExportJson = () => {
    const exportData = {
      dealSummary: deal,
      underwritingMetrics: metrics,
      interestRateHikeSimulationPct: rateHike,
      analystNotes,
      creditOfficerSignOff: signOffName,
      timestamp: new Date().toISOString(),
      engineVersion: 'SpreadSense AI v1.0',
    };

    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(exportData, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${deal.id}_Credit_Memo_Package.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();

    setIsExported(true);
    setTimeout(() => setIsExported(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-md animate-fadeIn">
      <div className="w-full max-w-4xl max-h-[90vh] overflow-y-auto glass-dock rounded-3xl p-8 shadow-[0_30px_90px_rgba(0,0,0,0.25)] border border-white/60 relative">
        
        {/* Top Actions */}
        <div className="flex items-start justify-between pb-6 border-b border-black/[0.06]">
          <div>
            <div className="flex items-center gap-2">
              <div className="p-2 rounded-xl bg-slate-900 text-amber-300">
                <FileCheck className="w-5 h-5" />
              </div>
              <h3 className="text-lg font-bold text-[#0D0D0D] tracking-tight">
                Institutional Credit Underwriting Memo
              </h3>
            </div>
            <p className="text-xs text-[#6E6D7A] mt-1">
              Generated by SpreadSense AI Automated Spreading Engine • Ready for Credit Committee Review
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3.5 py-2 text-xs font-semibold text-[#3A3945] rounded-xl bg-white/70 hover:bg-white transition-all shadow-sm border border-black/[0.04]"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Memo</span>
            </button>

            <button
              onClick={handleExportJson}
              className="flex items-center gap-1.5 px-3.5 py-2 text-xs font-semibold text-white rounded-xl bg-[#0D0D0D] hover:bg-[#2A2935] transition-all shadow-md"
            >
              <Download className="w-3.5 h-3.5 text-amber-300" />
              <span>{isExported ? 'Downloaded!' : 'Export JSON Package'}</span>
            </button>

            <button
              onClick={onClose}
              className="p-2 rounded-full hover:bg-black/[0.05] text-[#6E6D7A] transition-colors ml-2"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Memo Content Body */}
        <div className="space-y-6 mt-6 text-[#1F2937]">
          
          {/* Executive Summary Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 bg-white/60 p-5 rounded-2xl border border-black/[0.04] text-xs">
            <div>
              <span className="text-[#6E6D7A] font-semibold uppercase tracking-wider block text-[10px]">Borrower Entity</span>
              <strong className="text-sm text-[#0D0D0D] font-bold block mt-0.5">{deal.borrowerName}</strong>
              <span className="text-[#6E6D7A] block mt-0.5">{deal.industry} (SIC: {deal.sicCode})</span>
            </div>

            <div>
              <span className="text-[#6E6D7A] font-semibold uppercase tracking-wider block text-[10px]">Requested Facility</span>
              <strong className="text-sm text-[#0D0D0D] font-bold block mt-0.5">{formatCurrency(deal.facilityAmount)}</strong>
              <span className="text-[#6E6D7A] block mt-0.5">{deal.facilityType} @ Base {deal.baseInterestRate}%</span>
            </div>

            <div>
              <span className="text-[#6E6D7A] font-semibold uppercase tracking-wider block text-[10px]">Covenant Compliance Status</span>
              <div className="flex items-center gap-2 mt-1">
                <span className={`px-2.5 py-0.5 rounded-full text-xs font-bold ${
                  metrics.covenantVerdict === 'PASS'
                    ? 'bg-emerald-100 text-emerald-800 ring-1 ring-emerald-300'
                    : 'bg-amber-100 text-amber-800'
                }`}>
                  {metrics.covenantVerdict} ({formatRatio(metrics.dscr.fy2025)})
                </span>
                <span className="text-[11px] text-[#6E6D7A]">(Min: {deal.covenantMinDSCR}x)</span>
              </div>
            </div>
          </div>

          {/* Historical Spread Summary Table */}
          <div className="rounded-2xl bg-white/70 p-5 border border-black/[0.04]">
            <h4 className="text-xs font-bold uppercase tracking-wider text-[#6E6D7A] mb-3">
              Three-Period Financial Spreading Summary
            </h4>
            
            <table className="w-full text-xs text-left border-collapse">
              <thead>
                <tr className="border-b border-black/[0.08] text-[11px] font-bold text-[#6E6D7A]">
                  <th className="py-2">Standardized Metric</th>
                  <th className="py-2 text-right">FY 2023</th>
                  <th className="py-2 text-right">FY 2024</th>
                  <th className="py-2 text-right text-indigo-950 font-bold">FY 2025 (Projected)</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-black/[0.03] font-mono">
                <tr>
                  <td className="py-2 font-sans font-medium text-[#0D0D0D]">Net Revenue</td>
                  <td className="py-2 text-right">{formatCurrency(metrics.grossRevenue.fy2023)}</td>
                  <td className="py-2 text-right">{formatCurrency(metrics.grossRevenue.fy2024)}</td>
                  <td className="py-2 text-right font-bold text-indigo-950">{formatCurrency(metrics.grossRevenue.fy2025)}</td>
                </tr>
                <tr>
                  <td className="py-2 font-sans font-medium text-[#0D0D0D]">Gross Profit</td>
                  <td className="py-2 text-right">{formatCurrency(metrics.grossProfit.fy2023)}</td>
                  <td className="py-2 text-right">{formatCurrency(metrics.grossProfit.fy2024)}</td>
                  <td className="py-2 text-right font-bold text-indigo-950">{formatCurrency(metrics.grossProfit.fy2025)}</td>
                </tr>
                <tr>
                  <td className="py-2 font-sans font-medium text-[#0D0D0D]">Operating Income (EBIT)</td>
                  <td className="py-2 text-right">{formatCurrency(metrics.operatingIncomeEbit.fy2023)}</td>
                  <td className="py-2 text-right">{formatCurrency(metrics.operatingIncomeEbit.fy2024)}</td>
                  <td className="py-2 text-right font-bold text-indigo-950">{formatCurrency(metrics.operatingIncomeEbit.fy2025)}</td>
                </tr>
                <tr className="bg-indigo-50/50">
                  <td className="py-2 font-sans font-bold text-[#0D0D0D]">Adjusted EBITDA (w/ Addbacks)</td>
                  <td className="py-2 text-right font-bold">{formatCurrency(metrics.adjustedEbitda.fy2023)}</td>
                  <td className="py-2 text-right font-bold">{formatCurrency(metrics.adjustedEbitda.fy2024)}</td>
                  <td className="py-2 text-right font-bold text-indigo-950">{formatCurrency(metrics.adjustedEbitda.fy2025)}</td>
                </tr>
                <tr>
                  <td className="py-2 font-sans font-medium text-[#0D0D0D]">Total Debt Service (Annual)</td>
                  <td className="py-2 text-right">{formatCurrency(metrics.totalDebtService.fy2023)}</td>
                  <td className="py-2 text-right">{formatCurrency(metrics.totalDebtService.fy2024)}</td>
                  <td className="py-2 text-right font-bold text-indigo-950">{formatCurrency(metrics.totalDebtService.fy2025)}</td>
                </tr>
                <tr className="bg-emerald-50/50">
                  <td className="py-2 font-sans font-bold text-emerald-950">Debt Service Coverage Ratio (DSCR)</td>
                  <td className="py-2 text-right font-bold text-emerald-950">{formatRatio(metrics.dscr.fy2023)}</td>
                  <td className="py-2 text-right font-bold text-emerald-950">{formatRatio(metrics.dscr.fy2024)}</td>
                  <td className="py-2 text-right font-bold text-emerald-950 text-sm">{formatRatio(metrics.dscr.fy2025)}</td>
                </tr>
              </tbody>
            </table>
          </div>

          {/* Underwriter Qualitative Commentary */}
          <div className="rounded-2xl bg-white/70 p-5 border border-black/[0.04]">
            <h4 className="text-xs font-bold uppercase tracking-wider text-[#6E6D7A] mb-2">
              Credit Analyst Underwriting Narrative & Mitigants
            </h4>
            <textarea
              rows={3}
              value={analystNotes}
              onChange={(e) => setAnalystNotes(e.target.value)}
              className="w-full text-xs p-3 rounded-xl bg-slate-50 border border-black/[0.06] text-[#0D0D0D] focus:outline-none focus:ring-1 focus:ring-indigo-500"
            />
          </div>

          {/* Sign-off Block */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
            <div>
              <label className="text-[10px] font-bold text-[#6E6D7A] uppercase block mb-1">
                Underwriting Officer Sign-Off
              </label>
              <input
                type="text"
                value={signOffName}
                onChange={(e) => setSignOffName(e.target.value)}
                className="w-full text-xs font-semibold p-2.5 rounded-xl bg-white/70 border border-black/[0.06] text-[#0D0D0D]"
              />
            </div>
            <div>
              <label className="text-[10px] font-bold text-[#6E6D7A] uppercase block mb-1">
                Recommendation Timestamp
              </label>
              <div className="text-xs font-mono py-2.5 px-3 rounded-xl bg-slate-100/80 text-[#3A3945]">
                {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} • AI Verified
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
};
